/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    'slider-dashboard': SliderDashboard;
    ekstrakurikuler: Ekstrakurikuler;
    ppid: Ppid;
    'delete-requests': DeleteRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'slider-dashboard': SliderDashboardSelect<false> | SliderDashboardSelect<true>;
    ekstrakurikuler: EkstrakurikulerSelect<false> | EkstrakurikulerSelect<true>;
    ppid: PpidSelect<false> | PpidSelect<true>;
    'delete-requests': DeleteRequestsSelect<false> | DeleteRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category?: ('kegiatan' | 'prestasi' | 'profil' | 'ekskul' | 'ppid' | 'lainnya') | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Kelola berita dan informasi sekolah
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Otomatis dibuat dari judul. Contoh: kegiatan-class-meeting-2024
   */
  slug?: string | null;
  status: 'draft' | 'published' | 'archived';
  category: 'kegiatan_umum' | 'prestasi' | 'kegiatan_organisasi';
  publishedAt?: string | null;
  author?: (number | null) | User;
  /**
   * Ukuran ideal: 1200x630px. Format: JPG/WebP
   */
  featuredImage: number | Media;
  /**
   * Ditampilkan di daftar berita. Maks 300 karakter.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Tambahkan foto-foto pendukung berita
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Contoh: lomba, juara, nasional
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Centang agar berita ini muncul di slider homepage
   */
  showInSlider?: boolean | null;
  /**
   * Editor mengirim permintaan hapus ke admin
   */
  deleteRequested?: boolean | null;
  deleteRequestNote?: string | null;
  /**
   * Pengaturan SEO untuk mesin pencari
   */
  seo?: {
    /**
     * Maks 60 karakter. Kosongkan untuk pakai judul berita.
     */
    metaTitle?: string | null;
    /**
     * Maks 160 karakter. Kosongkan untuk pakai ringkasan.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Kelola foto slider di halaman utama (bergeser tiap 5 detik)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider-dashboard".
 */
export interface SliderDashboard {
  id: number;
  /**
   * Judul yang tampil di atas foto slider
   */
  title: string;
  /**
   * Deskripsi singkat yang tampil di bawah judul. Maks 150 karakter.
   */
  description?: string | null;
  /**
   * Ukuran ideal: 1920x700px (landscape). Format: JPG/WebP
   */
  image: number | Media;
  /**
   * Jika diisi, slide bisa diklik dan mengarah ke halaman berita
   */
  linkTo?: {
    type?: ('none' | 'post' | 'custom') | null;
    post?: (number | null) | Post;
    /**
     * Contoh: /berita/kegiatan-class-meeting
     */
    url?: string | null;
  };
  /**
   * Angka kecil tampil lebih dulu. 0 = pertama.
   */
  order?: number | null;
  /**
   * Uncheck untuk menyembunyikan slide tanpa menghapus
   */
  isActive?: boolean | null;
  /**
   * Opsional: atur kapan slide mulai/selesai ditampilkan
   */
  schedule?: {
    startDate?: string | null;
    endDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola data ekstrakurikuler sekolah
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ekstrakurikuler".
 */
export interface Ekstrakurikuler {
  id: number;
  name: string;
  category?:
    | (
        | 'olahraga'
        | 'seni_budaya'
        | 'akademik'
        | 'kepemimpinan'
        | 'teknologi'
        | 'lingkungan'
        | 'musik'
        | 'keagamaan'
        | 'keterampilan'
      )
    | null;
  /**
   * Foto utama atau logo ekstrakurikuler. Ideal: 800x600px
   */
  coverImage?: (number | null) | Media;
  /**
   * Nama lengkap guru pembina
   */
  pembina: string;
  /**
   * NIP pembina (opsional)
   */
  pembinaNIP?: string | null;
  schedule?: {
    hari?: ('senin' | 'selasa' | 'rabu' | 'kamis' | 'jumat' | 'sabtu')[] | null;
    /**
     * Contoh: 14.00 – 16.00 WIB
     */
    waktu?: string | null;
    /**
     * Contoh: Lapangan Basket, Aula, Lab Komputer
     */
    tempat?: string | null;
  };
  /**
   * Deskripsi lengkap ekskul, sejarah, tujuan, dll.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Prestasi yang pernah diraih ekskul ini
   */
  achievements?:
    | {
        title: string;
        year?: string | null;
        level?: ('sekolah' | 'kecamatan' | 'kota' | 'provinsi' | 'nasional' | 'internasional') | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck untuk menyembunyikan dari website
   */
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola dokumen dan informasi PPID (Pejabat Pengelola Informasi dan Dokumentasi)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ppid".
 */
export interface Ppid {
  id: number;
  title: string;
  category:
    | 'profil_ppid'
    | 'sk'
    | 'tugas_fungsi'
    | 'maklumat'
    | 'jam_layanan'
    | 'alur_permohonan'
    | 'mou'
    | 'sop'
    | 'daftar_informasi';
  /**
   * Contoh: 001/PPID/SMPN8/2024
   */
  documentNumber?: string | null;
  documentDate?: string | null;
  /**
   * Contoh: 1.0, 2.1, Rev.3
   */
  version?: string | null;
  /**
   * Konten artikel atau deskripsi dokumen
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Upload file dokumen (PDF, Word, Excel, dll.)
   */
  attachments?:
    | {
        file: number | Media;
        /**
         * Nama tampil tombol download. Contoh: "Download SK PPID 2024"
         */
        fileLabel?: string | null;
        fileDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Otomatis bertambah setiap file didownload
   */
  downloadCount?: number | null;
  /**
   * Uncheck untuk menyembunyikan dari publik
   */
  isPublished?: boolean | null;
  /**
   * Angka kecil tampil lebih dulu dalam kategorinya
   */
  order?: number | null;
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Permintaan hapus artikel dari editor — hanya admin yang bisa menyetujui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delete-requests".
 */
export interface DeleteRequest {
  id: number;
  docTitle: string;
  collectionSlug: 'posts' | 'slider-dashboard' | 'ekstrakurikuler' | 'ppid';
  docId: string;
  /**
   * Ubah ke "Disetujui" untuk menghapus dokumen asli, atau "Ditolak" untuk menolak permintaan.
   */
  status?: ('pending' | 'approved' | 'rejected') | null;
  requestedAt?: string | null;
  /**
   * Catatan internal admin (tidak dilihat editor)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'slider-dashboard';
        value: number | SliderDashboard;
      } | null)
    | ({
        relationTo: 'ekstrakurikuler';
        value: number | Ekstrakurikuler;
      } | null)
    | ({
        relationTo: 'ppid';
        value: number | Ppid;
      } | null)
    | ({
        relationTo: 'delete-requests';
        value: number | DeleteRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  showInSlider?: T;
  deleteRequested?: T;
  deleteRequestNote?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider-dashboard_select".
 */
export interface SliderDashboardSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  linkTo?:
    | T
    | {
        type?: T;
        post?: T;
        url?: T;
      };
  order?: T;
  isActive?: T;
  schedule?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ekstrakurikuler_select".
 */
export interface EkstrakurikulerSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  coverImage?: T;
  pembina?: T;
  pembinaNIP?: T;
  schedule?:
    | T
    | {
        hari?: T;
        waktu?: T;
        tempat?: T;
      };
  description?: T;
  achievements?:
    | T
    | {
        title?: T;
        year?: T;
        level?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ppid_select".
 */
export interface PpidSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  documentNumber?: T;
  documentDate?: T;
  version?: T;
  content?: T;
  attachments?:
    | T
    | {
        file?: T;
        fileLabel?: T;
        fileDescription?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  downloadCount?: T;
  isPublished?: T;
  order?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delete-requests_select".
 */
export interface DeleteRequestsSelect<T extends boolean = true> {
  docTitle?: T;
  collectionSlug?: T;
  docId?: T;
  status?: T;
  requestedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Pengaturan global: alamat sekolah, media sosial, visi misi, kepala sekolah
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  schoolName?: string | null;
  schoolNSS?: string | null;
  schoolNPSN?: string | null;
  /**
   * Format PNG transparan. Ideal: 400x400px
   */
  schoolLogo?: (number | null) | Media;
  address?: {
    /**
     * Contoh: Jl. Mastrip No.XX
     */
    street?: string | null;
    kelurahan?: string | null;
    kecamatan?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    /**
     * URL Google Maps embed atau share link
     */
    mapsUrl?: string | null;
  };
  contact?: {
    /**
     * Contoh: (0335) 123456
     */
    phone?: string | null;
    /**
     * Format: 628xxxxxxxxxx
     */
    whatsapp?: string | null;
    email?: string | null;
    website?: string | null;
  };
  /**
   * Kosongkan jika tidak ada. Icon akan otomatis tampil jika diisi.
   */
  socialMedia?: {
    /**
     * Contoh: https://facebook.com/smpn8probolinggo
     */
    facebook?: string | null;
    /**
     * Contoh: https://instagram.com/smpn8prob
     */
    instagram?: string | null;
    /**
     * Contoh: https://youtube.com/@smpn8prob
     */
    youtube?: string | null;
    twitter?: string | null;
    tiktok?: string | null;
  };
  principal?: {
    /**
     * Lengkap dengan gelar. Contoh: Drs. Ahmad Fauzi, M.Pd.
     */
    name?: string | null;
    nip?: string | null;
    /**
     * Foto formal. Ideal: 400x500px (portrait)
     */
    photo?: (number | null) | Media;
    /**
     * Kutipan atau sambutan singkat kepsek untuk ditampilkan di homepage
     */
    message?: string | null;
  };
  /**
   * Visi sekolah yang ditampilkan di homepage dan halaman profil
   */
  vision?: string | null;
  /**
   * Tambahkan poin-poin misi sekolah
   */
  mission?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Contoh: Berprestasi, Berkarakter, Berwawasan Global
   */
  motto?: string | null;
  /**
   * Teks yang berjalan di bagian atas halaman utama
   */
  tickerText?: string | null;
  tickerEnabled?: boolean | null;
  /**
   * Teks positif yang tampil di depan foto slider homepage
   */
  heroTaglines?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Gambar yang muncul saat link dibagikan di medsos. Ideal: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Contoh: G-XXXXXXXXXX
     */
    googleAnalyticsId?: string | null;
  };
  /**
   * Pilih tampilan visual website...
   */
  activeTheme?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  schoolName?: T;
  schoolNSS?: T;
  schoolNPSN?: T;
  schoolLogo?: T;
  address?:
    | T
    | {
        street?: T;
        kelurahan?: T;
        kecamatan?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        mapsUrl?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        website?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        twitter?: T;
        tiktok?: T;
      };
  principal?:
    | T
    | {
        name?: T;
        nip?: T;
        photo?: T;
        message?: T;
      };
  vision?: T;
  mission?:
    | T
    | {
        point?: T;
        id?: T;
      };
  motto?: T;
  tickerText?: T;
  tickerEnabled?: T;
  heroTaglines?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        googleAnalyticsId?: T;
      };
  activeTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}